# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0010_valuecountresult_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationlayer',
            name='parse_log',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='aggregationlayer',
            name='shapefile',
            field=models.FileField(upload_to='shapefiles/aggregationlayers'),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='grouping',
            field=models.TextField(default='auto'),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='units',
            field=models.TextField(default=''),
        ),
    ]
