# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 06:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0011_auto_20170530_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuecountresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Computing'), (2, 'Finished'), (3, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
