# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0012_auto_20170530_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuecountresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Computing'), (2, 'Finished'), (3, 'Failed'), (4, 'Outdated')], default=0),
        ),
    ]
