# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 06:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0015_auto_20170626_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationarea',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AddField(
            model_name='aggregationlayer',
            name='fields',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='aggregationlayer',
            name='nr_of_areas',
            field=models.IntegerField(default=0),
        ),
    ]
