# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0016_auto_20170831_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuecountresult',
            name='stats_cumsum_t0',
            field=models.FloatField(blank=True, editable=False, help_text='Nr of pixels counted.', null=True),
        ),
        migrations.AddField(
            model_name='valuecountresult',
            name='stats_cumsum_t1',
            field=models.FloatField(blank=True, editable=False, help_text='Sum of pixel values.', null=True),
        ),
        migrations.AddField(
            model_name='valuecountresult',
            name='stats_cumsum_t2',
            field=models.FloatField(blank=True, editable=False, help_text='Sum of squares of pixel values.', null=True),
        ),
    ]
