# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 04:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0019_auto_20180302_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationlayer',
            name='extent',
            field=django.contrib.gis.db.models.fields.PolygonField(editable=False, null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='aggregationlayer',
            name='nr_of_areas',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
