# Generated by Django 2.1.7 on 2019-09-05 07:54

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0020_auto_20180308_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationarea',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='aggregationlayer',
            name='fields',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
