# Generated by Django 2.1.7 on 2019-11-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0022_auto_20191105_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationlayer',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Unprocessed', max_length=20),
        ),
    ]
