# Generated by Django 2.2.10 on 2020-03-05 04:49

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0023_aggregationlayer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuecountresult',
            name='stats_avg',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='stats_max',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='stats_min',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='stats_std',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuecountresult',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(db_index=True, default=dict),
        ),
    ]
