# Generated by Django 2.2.10 on 2020-04-17 03:37

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0024_auto_20200305_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationarea',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
